name: Node.js CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Prepare Yarn
      run: corepack enable  
    - name: Install dependencies
      run: yarn install
    - name: Set Git user
      run: |
        git config --global user.email "user@example.com"
        git config --global user.name "Example User"

    - name: Run tests
      run: yarn test
    - name: Run semantic-release in dry run
      if: github.event_name == 'push'
      id: dry-release
      run: unset GITHUB_ACTIONS && yarn run semantic-release --dry-run --no-ci --branches ${REF_NAME}
      env:
          REF_NAME: ${{ github.ref_name }}